### ISSUE TITLE
Generating

### ISSUE THREAD

**Issue by ferdyandannes** [zappyfish/vadl-training#1]
Hello may I ask you something??
I tried to train the struct2depth from the tensorflow repositories, but I couldn't find how to generate the train.txt file and I found your repository with the train.txt file. How do you generate the train.txt file??

And what command did you use?? because when I use 
python train.py \
  --logtostderr \
  --checkpoint_dir D:\Kuliah\S2\Depth_Estimation\models-master\research\struct2depth\train_checkpoint \
  --data_dir D:\Kuliah\S2\Depth_Estimation\models-master\research\struct2depth\kitti-raw-uncompressed \
  --architecture resnet \
  --imagenet_ckpt resnet_pretrained/model.ckpt \
  --imagenet_norm true \
  --joint_encoder false

it give error : 
File "train.py", line 123, in main
    raise ValueError('Using a joint encoder is currently not supported when '
ValueError: Using a joint encoder is currently not supported when modeling object motion.

Thank you

**Comment by zappyfish** [comment]
Hi,

I had to edit some of the scripts a bit to get things working for me. Because of that, I am not absolutely sure that what I did is correct, but based on my training results, it seems to have worked. Here is what I did:

1. Make sure you have a pretrained imagenet model. Some options include:

- resnet-18-tensorflow https://github.com/dalgu90/resnet-18-tensorflow
- the KITTI pretrained struct2depth model https://drive.google.com/file/d/1mjb4ioDRH8ViGbui52stSUDwhkGrDXy8/view
- the cityscapes pretrained struct2depth model 
https://drive.google.com/file/d/1-BNr_jlOmhu39z1Un9zEZ63eFncZ8lzH/view

2. Gather data and organize it in directories. Depending on how you've structured your data, you might have to edit the gen_data_* script you are using a bit. An example that has worked for me is running the gen_data_lab.py script on the ss2_data directory (both are in this repo). If you want to preprocess the data using a different input data directory and a different output data directory, then you'll have to change the variables INPUT_DIR and OUTPUT_DIR in gen_data_lab.py. Currently they are set to "./ss2_data" and "./processed_ss2_data".

Also, It looks like you are using the KITTI dataset. If that is the case, note that I don't think training from the KITTI pretrained model will get you anywhere further. If all you want to do is use the model to run inference, you may not even have to train if you just download that model.

3. At this point, you should be ready to run training. I had to make some edits to the training scripts to get things to run properly, and those edits should be in this repository (I believe). I run the following command:


python train.py \
  --logtostderr \
  --checkpoint_dir $ckpt_dir \
  --data_dir $data_dir \
  --architecture resnet \
  --imagenet_ckpt $imagenet_ckpt \
  --imagenet_norm true \
  --joint_encoder false

I will call out a couple things about this:

First, I edited the training scripts to expect JPG files instead of PNG files, so keep that in mind. If you use the files in this repo, you will need to change that back. I set ckpt_dir to {PATH_TO_REPO}/checkpoints, I set imagenet_ckpt to one of the models I mentioned in (1) and data_dir was set to {PATH_TO_REPO}/processed_ss2_data.

I think this was everything, but please let me know if this does not help!

**Comment by ferdyandannes** [comment]
> Hi,
> 
> I had to edit some of the scripts a bit to get things working for me. Because of that, I am not absolutely sure that what I did is correct, but based on my training results, it seems to have worked. Here is what I did:
> 
> 1. Make sure you have a pretrained imagenet model. Some options include:
> 
> * resnet-18-tensorflow https://github.com/dalgu90/resnet-18-tensorflow
> * the KITTI pretrained struct2depth model https://drive.google.com/file/d/1mjb4ioDRH8ViGbui52stSUDwhkGrDXy8/view
> * the cityscapes pretrained struct2depth model
>   https://drive.google.com/file/d/1-BNr_jlOmhu39z1Un9zEZ63eFncZ8lzH/view
> 
> 1. Gather data and organize it in directories. Depending on how you've structured your data, you might have to edit the gen_data_* script you are using a bit. An example that has worked for me is running the gen_data_lab.py script on the ss2_data directory (both are in this repo). If you want to preprocess the data using a different input data directory and a different output data directory, then you'll have to change the variables INPUT_DIR and OUTPUT_DIR in gen_data_lab.py. Currently they are set to "./ss2_data" and "./processed_ss2_data".
> 
> Also, It looks like you are using the KITTI dataset. If that is the case, note that I don't think training from the KITTI pretrained model will get you anywhere further. If all you want to do is use the model to run inference, you may not even have to train if you just download that model.
> 
> 1. At this point, you should be ready to run training. I had to make some edits to the training scripts to get things to run properly, and those edits should be in this repository (I believe). I run the following command:
> 
> python train.py 
> --logtostderr 
> --checkpoint_dir $ckpt_dir 
> --data_dir $data_dir 
> --architecture resnet 
> --imagenet_ckpt $imagenet_ckpt 
> --imagenet_norm true 
> --joint_encoder false
> 
> I will call out a couple things about this:
> 
> First, I edited the training scripts to expect JPG files instead of PNG files, so keep that in mind. If you use the files in this repo, you will need to change that back. I set ckpt_dir to {PATH_TO_REPO}/checkpoints, I set imagenet_ckpt to one of the models I mentioned in (1) and data_dir was set to {PATH_TO_REPO}/processed_ss2_data.
> 
> I think this was everything, but please let me know if this does not help!

Thank you for respond my question
I have try to train with your dataset, it runs successfully but it seems my GPU memory is too small, so it goes CUDA out of memory.
so in you training command --imagenet_ckpt $imagenet_ckpt  , $imagenet_ckpt you filled it from the resnet-18-tensorflow???

**Comment by zappyfish** [comment]
Yes, I used the resnet-18-tensorflow for the imagenet_ckpt. 

I have also found that the training process is very memory hungry, and I could not perform it at first for the same reason. I had to reach out to a professor at my school to get access to more powerful compute resources to get training working.

**Comment by ferdyandannes** [comment]
> Yes, I used the resnet-18-tensorflow for the imagenet_ckpt.
> 
> I have also found that the training process is very memory hungry, and I could not perform it at first for the same reason. I had to reach out to a professor at my school to get access to more powerful compute resources to get training working.

Okay Thank you for this very useful information
Sorry for interrupting you
